# Generated by Django 3.2.2 on 2021-05-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=32)),
                ('token_id', models.PositiveIntegerField()),
                ('code', models.CharField(max_length=8)),
                ('gdp', models.DecimalField(decimal_places=0, max_digits=32)),
                ('area', models.DecimalField(decimal_places=0, max_digits=32)),
                ('population', models.DecimalField(decimal_places=0, max_digits=32)),
                ('crypto_index', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('price', models.DecimalField(decimal_places=18, max_digits=32)),
            ],
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enum', models.CharField(choices=[('mercury', 'Mercury'), ('venus', 'Venus'), ('mars', 'Mars'), ('jupiter', 'Jupiter'), ('saturn', 'Saturn'), ('uranus', 'Uranus'), ('neptune', 'Neptune')], max_length=8)),
                ('number', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=32)),
                ('token_id', models.PositiveIntegerField()),
                ('sun_distance', models.DecimalField(decimal_places=0, max_digits=32)),
                ('weight', models.DecimalField(decimal_places=0, max_digits=32)),
                ('price', models.DecimalField(decimal_places=18, max_digits=32)),
            ],
        ),
    ]
